"""add_tool_models

Revision ID: 6ae3ffd4b290
Revises: 06b478a39bb6
Create Date: 2026-10-01 23:48:22.633671
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ae3ffd4b290"
down_revision: str | None = "06b478a39bb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tools",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "SUSPENDED", "DEACTIVATED", name="toolstatus"),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="toolrisklevel"),
            nullable=False,
        ),
        sa.Column("access_type", sa.Enum("READ", "WRITE", name="toolaccesstype"), nullable=False),
        sa.Column(
            "reversibility",
            sa.Enum("REVERSIBLE", "IRREVERSIBLE", name="toolreversibility"),
            nullable=False,
        ),
        sa.Column(
            "data_classification",
            sa.Enum(
                "PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED", name="tooldataclassification"
            ),
            nullable=False,
        ),
        sa.Column(
            "approval_requirement",
            sa.Enum("NOT_REQUIRED", "OPTIONAL", "REQUIRED", name="toolapprovalrequirement"),
            nullable=False,
        ),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_tool_org_slug"),
    )
    op.create_index(op.f("ix_tools_organization_id"), "tools", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tools_owner_user_id"), "tools", ["owner_user_id"], unique=False)
    op.create_table(
        "agent_tool_permissions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "tool_id", name="uq_agent_tool"),
    )
    op.create_index(
        op.f("ix_agent_tool_permissions_agent_id"),
        "agent_tool_permissions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tool_permissions_tool_id"),
        "agent_tool_permissions",
        ["tool_id"],
        unique=False,
    )
    op.create_table(
        "tool_versions",
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_schema", sa.JSON(), nullable=True),
        sa.Column("output_schema", sa.JSON(), nullable=True),
        sa.Column("configuration_metadata", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "RETIRED", name="toolversionstatus"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_id", "version", name="uq_tool_version"),
    )
    op.create_index(op.f("ix_tool_versions_tool_id"), "tool_versions", ["tool_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_versions_tool_id"), table_name="tool_versions")
    op.drop_table("tool_versions")
    op.drop_index(op.f("ix_agent_tool_permissions_tool_id"), table_name="agent_tool_permissions")
    op.drop_index(op.f("ix_agent_tool_permissions_agent_id"), table_name="agent_tool_permissions")
    op.drop_table("agent_tool_permissions")
    op.drop_index(op.f("ix_tools_owner_user_id"), table_name="tools")
    op.drop_index(op.f("ix_tools_organization_id"), table_name="tools")
    op.drop_table("tools")
    # ### end Alembic commands ###
